version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672' # JMS 端口
      - '15672:15672' # 管理端口 default user:pass = guest:guest
    networks:
      - docker-app
  discovery:
    image: twigcodes/twig-discovery
    ports:
    - 8761:8761
    environment:
      SERVER_PORT: 8761
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
    - rabbitmq
    networks:
    - docker-app
volumes:
  pgdata: {}
networks:
  docker-app:
    driver: bridge
