spring:
  profiles:
    active: dev
  cloud:
    config:
      uri: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/config
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
management:
  endpoints.web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
zuul:
  prefix: /api
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: '*'
  routes:
    demoa:
      path: /demoa/**
      serviceId: demoa
      strip-prefix: true
    demob:
      path: /demob/**
      serviceId: demob
      strip-prefix: true
keycloak:
  realm: ${KEYCLOAK_REALM:twigcodes}
  auth-server-url: https://${KEYCLOAK_HOST:auth.twigcodes.com}/auth
  ssl-required: external
  resource: ${OAUTH2_CLIENT_ID:login-app}
  principal-attribute: preferred_username
  credentials:
    secret: 942bfe03-9851-4db8-b100-8393c9c6c9cd
---
spring:
  profiles: local
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false
---
spring:
  profiles: dev
zuul:
  include-debug-header: true
logging:
  level:
    org.apache.http: 'OFF'
    org.springframework: DEBUG
    org.springframework.security: TRACE
    com.netflix.discovery: 'OFF'
    com.netflix.eureka: 'OFF'
    com.netflix.zuul: 'OFF'
    com.twigcodes.gateway: 'OFF'
    org.keycloak: TRACE
---
spring:
  profiles: prod
eureka:
  instance:
    hostname: gateway
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:discovery}:${DISCOVERY_PORT:8761}/eureka/
